name: Build and Deploy

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsque vous poussez sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests\unitaires\test_app.py

      - name: Deploy to production
        # Ajoutez ici vos étapes de déploiement
        run: |
          echo "Deploying to production..."
          # Commandes de déploiement
      # Vous pouvez ajouter d'autres jobs ou étapes ici pour votre workflow